export interface Tool {
  id: string;
  name: string;
  description: string;
  href: string;
  icon: string; // 改为字符串，存储图标名称
  category: string;
  popular?: boolean;
  new?: boolean; // 新增：标记新工具
  tags?: string[]; // 新增：工具标签，便于搜索
  difficulty?: 'beginner' | 'intermediate' | 'advanced'; // 新增：难度等级
  estimatedTime?: string; // 新增：预估使用时间
}

export const tools: Tool[] = [
  // AI工具
  {
    id: 'ai-text-generator',
    name: '文本生成器',
    description: '生成Lorem ipsum、假数据、随机文本等，支持多种生成类型。',
    href: '/tools/ai/text-generator',
    icon: 'MessageSquare',
    category: 'ai',
    popular: true,
    tags: ['文本', '生成', '假数据', 'lorem'],
    difficulty: 'beginner',
    estimatedTime: '1-2分钟',
  },
  {
    id: 'ai-language-detect',
    name: '语言检测',
    description: '自动识别文本的语言类型，支持中英日韩法德西俄阿等多种语言。',
    href: '/tools/ai/language-detect',
    icon: 'Brain',
    category: 'ai',
    popular: true,
    tags: ['语言', '检测', '识别', '国际化'],
    difficulty: 'beginner',
    estimatedTime: '即时',
  },
  {
    id: 'ai-keyword-extract',
    name: '关键词提取',
    description: '从文本中智能提取关键词和短语，提供频率统计和重要性评分。',
    href: '/tools/ai/keyword-extract',
    icon: 'Hash',
    category: 'ai',
    popular: true,
    tags: ['关键词', '提取', 'SEO', '分析'],
    difficulty: 'intermediate',
    estimatedTime: '1-3分钟',
  },
  {
    id: 'ai-text-summary',
    name: '智能摘要',
    description: '提取文本关键信息，生成简洁摘要（即将推出）。',
    href: '/tools/ai/text-summary',
    icon: 'Sparkles',
    category: 'ai',
    popular: false,
    new: true,
    tags: ['摘要', '总结', 'AI', '文本分析'],
    difficulty: 'intermediate',
    estimatedTime: '2-5分钟',
  },
  {
    id: 'ai-sentiment-analysis',
    name: '情感分析',
    description: '分析文本的情感倾向和语调（即将推出）。',
    href: '/tools/ai/sentiment-analysis',
    icon: 'TrendingUp',
    category: 'ai',
    popular: false,
    new: true,
    tags: ['情感', '分析', '情绪', '舆情'],
    difficulty: 'intermediate',
    estimatedTime: '1-3分钟',
  },
  // 新增AI工具
  {
    id: 'ai-text-translator',
    name: 'AI翻译助手',
    description: '智能文本翻译，支持多种语言互译，保持语境和语调。',
    href: '/tools/ai/translator',
    icon: 'Languages',
    category: 'ai',
    popular: true,
    new: true,
    tags: ['翻译', '多语言', 'AI', '语言转换'],
    difficulty: 'beginner',
    estimatedTime: '即时',
  },
  {
    id: 'ai-content-optimizer',
    name: '内容优化器',
    description: '优化文章标题、描述和内容结构，提升SEO效果。',
    href: '/tools/ai/content-optimizer',
    icon: 'Zap',
    category: 'ai',
    popular: false,
    new: true,
    tags: ['SEO', '内容优化', '标题', '营销'],
    difficulty: 'intermediate',
    estimatedTime: '3-5分钟',
  },
  {
    id: 'text-case',
    name: '文本格式转换',
    description: '快速转换文本大小写、驼峰命名等格式，支持9种常用格式。',
    href: '/tools/text/case',
    icon: 'TextCursorInput',
    category: 'text',
    popular: true,
    tags: ['格式转换', '大小写', '驼峰', '编程'],
    difficulty: 'beginner',
    estimatedTime: '即时',
  },
  {
    id: 'text-encode',
    name: '编码解码工具',
    description: 'Base64、URL、HTML等编码解码工具，支持多种格式转换。',
    href: '/tools/text/encode',
    icon: 'Code',
    category: 'text',
    popular: false,
    tags: ['编码', '解码', 'Base64', 'URL', 'HTML'],
    difficulty: 'intermediate',
    estimatedTime: '即时',
  },
  {
    id: 'text-regex',
    name: '正则表达式测试',
    description: '在线测试和调试正则表达式，实时查看匹配结果。',
    href: '/tools/text/regex',
    icon: 'FileText',
    category: 'text',
    popular: true,
    tags: ['正则', '匹配', '测试', '开发'],
    difficulty: 'advanced',
    estimatedTime: '5-10分钟',
  },
  {
    id: 'text-analyze',
    name: '文本分析工具',
    description: '分析文本的字符数、词数、行数等统计信息。',
    href: '/tools/text/analyze',
    icon: 'FileText',
    category: 'text',
    popular: false,
    tags: ['分析', '统计', '字符数', '词数'],
    difficulty: 'beginner',
    estimatedTime: '即时',
  },
  {
    id: 'text-compare',
    name: '文本比较工具',
    description: '比较两段文本的差异，支持忽略大小写和空白字符。',
    href: '/tools/text/compare',
    icon: 'FileText',
    category: 'text',
    popular: false,
    tags: ['比较', '差异', '对比', '版本控制'],
    difficulty: 'intermediate',
    estimatedTime: '1-2分钟',
  },
  {
    id: 'text-deduplicate',
    name: '文本去重工具',
    description: '去除重复的文本行，支持多种去重模式。',
    href: '/tools/text/deduplicate',
    icon: 'FileText',
    category: 'text',
    popular: false,
    tags: ['去重', '清理', '数据处理'],
    difficulty: 'beginner',
    estimatedTime: '即时',
  },
  {
    id: 'text-stats',
    name: '文本统计工具',
    description: '统计文本的字符、单词、行数等详细信息。',
    href: '/tools/text/stats',
    icon: 'FileText',
    category: 'text',
    popular: false,
    tags: ['统计', '分析', '报告'],
    difficulty: 'beginner',
    estimatedTime: '即时',
  },
  // 新增文本工具
  {
    id: 'text-formatter',
    name: '文本格式化器',
    description: '智能格式化文本，调整段落、缩进、行距等格式。',
    href: '/tools/text/formatter',
    icon: 'AlignLeft',
    category: 'text',
    popular: false,
    new: true,
    tags: ['格式化', '段落', '排版', '编辑'],
    difficulty: 'beginner',
    estimatedTime: '1-2分钟',
  },
  {
    id: 'text-word-cloud',
    name: '词云生成器',
    description: '从文本生成词云图，可视化显示词频分布。',
    href: '/tools/text/word-cloud',
    icon: 'Cloud',
    category: 'text',
    popular: true,
    new: true,
    tags: ['词云', '可视化', '词频', '图表'],
    difficulty: 'intermediate',
    estimatedTime: '2-3分钟',
  },
  {
    id: 'image-compress',
    name: '图片压缩工具',
    description: '在线压缩图片，优化图片大小，支持质量调节。',
    href: '/tools/image/compress',
    icon: 'Image',
    category: 'image',
    popular: true,
    tags: ['压缩', '优化', '大小', '质量'],
    difficulty: 'beginner',
    estimatedTime: '1-2分钟',
  },
  {
    id: 'image-convert',
    name: '图片格式转换',
    description: '将图片转换为不同格式，支持JPEG、PNG、WebP等。',
    href: '/tools/image/convert',
    icon: 'Image',
    category: 'image',
    popular: false,
    tags: ['格式转换', 'JPEG', 'PNG', 'WebP'],
    difficulty: 'beginner',
    estimatedTime: '1-2分钟',
  },
  {
    id: 'image-watermark',
    name: '水印添加工具',
    description: '为图片添加文字水印，支持自定义位置、颜色、透明度等。',
    href: '/tools/image/watermark',
    icon: 'Image',
    category: 'image',
    popular: false,
    tags: ['水印', '保护', '品牌', '版权'],
    difficulty: 'intermediate',
    estimatedTime: '2-3分钟',
  },
  {
    id: 'image-resize',
    name: '图片尺寸调整',
    description: '调整图片尺寸，支持保持比例、批量处理等功能。',
    href: '/tools/image/resize',
    icon: 'Image',
    category: 'image',
    popular: false,
    tags: ['尺寸', '缩放', '批量', '比例'],
    difficulty: 'beginner',
    estimatedTime: '1-2分钟',
  },
  {
    id: 'image-filter',
    name: '图片滤镜工具',
    description: '为图片添加各种滤镜效果，支持亮度、对比度、饱和度调节。',
    href: '/tools/image/filter',
    icon: 'Image',
    category: 'image',
    popular: false,
    tags: ['滤镜', '效果', '亮度', '对比度', '饱和度'],
    difficulty: 'intermediate',
    estimatedTime: '2-5分钟',
  },
  // 新增图片工具
  {
    id: 'image-background-remover',
    name: '背景移除工具',
    description: '智能识别并移除图片背景，支持透明背景输出。',
    href: '/tools/image/background-remover',
    icon: 'Scissors',
    category: 'image',
    popular: true,
    new: true,
    tags: ['背景移除', '抠图', '透明', 'AI'],
    difficulty: 'beginner',
    estimatedTime: '1-3分钟',
  },
  {
    id: 'image-editor',
    name: '在线图片编辑器',
    description: '功能丰富的在线图片编辑器，支持裁剪、旋转、调色等。',
    href: '/tools/image/editor',
    icon: 'Edit',
    category: 'image',
    popular: true,
    new: true,
    tags: ['编辑', '裁剪', '旋转', '调色', '专业'],
    difficulty: 'intermediate',
    estimatedTime: '5-15分钟',
  },
  {
    id: 'dev-format',
    name: '代码格式化',
    description: '格式化JavaScript、JSON、CSS等代码，使其更易读。',
    href: '/tools/dev/format',
    icon: 'Code',
    category: 'dev',
    popular: true,
    tags: ['格式化', '代码', 'JavaScript', 'JSON', 'CSS'],
    difficulty: 'beginner',
    estimatedTime: '即时',
  },
  {
    id: 'dev-json',
    name: 'JSON工具',
    description: '格式化、验证、压缩JSON数据，支持自定义缩进。',
    href: '/tools/dev/json',
    icon: 'Code',
    category: 'dev',
    popular: false,
    tags: ['JSON', '验证', '格式化', '压缩'],
    difficulty: 'beginner',
    estimatedTime: '即时',
  },
  {
    id: 'dev-color',
    name: '颜色选择器',
    description: '选择颜色并获取多种格式的颜色值，支持RGB、HSL、HEX等格式。',
    href: '/tools/dev/color',
    icon: 'Palette',
    category: 'dev',
    popular: true,
    tags: ['颜色', 'RGB', 'HSL', 'HEX', '设计'],
    difficulty: 'beginner',
    estimatedTime: '1-2分钟',
  },
  {
    id: 'dev-api',
    name: 'API测试工具',
    description: '测试API接口，发送HTTP请求并查看响应结果。',
    href: '/tools/dev/api',
    icon: 'Send',
    category: 'dev',
    popular: true,
    tags: ['API', 'HTTP', '测试', '调试', '开发'],
    difficulty: 'intermediate',
    estimatedTime: '2-10分钟',
  },
  {
    id: 'dev-timestamp',
    name: '时间戳转换',
    description: '时间戳与日期时间相互转换，支持多种格式。',
    href: '/tools/dev/timestamp',
    icon: 'Clock',
    category: 'dev',
    popular: false,
    tags: ['时间戳', '日期', '时间', '转换'],
    difficulty: 'beginner',
    estimatedTime: '即时',
  },
  // 新增开发工具
  {
    id: 'dev-sql-formatter',
    name: 'SQL格式化器',
    description: '格式化SQL查询语句，提高代码可读性。',
    href: '/tools/dev/sql-formatter',
    icon: 'Database',
    category: 'dev',
    popular: false,
    new: true,
    tags: ['SQL', '格式化', '数据库', '查询'],
    difficulty: 'intermediate',
    estimatedTime: '即时',
  },
  {
    id: 'dev-regex-builder',
    name: '正则表达式构建器',
    description: '可视化构建正则表达式，提供常用模式和测试功能。',
    href: '/tools/dev/regex-builder',
    icon: 'Wrench',
    category: 'dev',
    popular: true,
    new: true,
    tags: ['正则', '构建器', '可视化', '模式'],
    difficulty: 'advanced',
    estimatedTime: '5-15分钟',
  },
  {
    id: 'dev-jwt-decoder',
    name: 'JWT解码器',
    description: '解码和验证JWT令牌，查看载荷内容。',
    href: '/tools/dev/jwt-decoder',
    icon: 'Key',
    category: 'dev',
    popular: false,
    new: true,
    tags: ['JWT', '解码', '令牌', '验证', '安全'],
    difficulty: 'intermediate',
    estimatedTime: '1-2分钟',
  },
  {
    id: 'utility-qr',
    name: '二维码生成器',
    description: '生成自定义二维码，支持文本和URL，可下载使用。',
    href: '/tools/utility/qr',
    icon: 'QrCode',
    category: 'utility',
    popular: true,
    tags: ['二维码', '生成', '下载', '分享'],
    difficulty: 'beginner',
    estimatedTime: '1分钟',
  },
  {
    id: 'utility-password',
    name: '密码生成器',
    description: '生成安全、随机的密码，支持自定义长度和字符类型。',
    href: '/tools/utility/password',
    icon: 'Shield',
    category: 'utility',
    popular: false,
    tags: ['密码', '安全', '随机', '生成'],
    difficulty: 'beginner',
    estimatedTime: '即时',
  },
  {
    id: 'utility-calculator',
    name: '计算器',
    description: '基础计算器，支持加减乘除等基本运算。',
    href: '/tools/utility/calculator',
    icon: 'Calculator',
    category: 'utility',
    popular: false,
    tags: ['计算器', '运算', '数学'],
    difficulty: 'beginner',
    estimatedTime: '即时',
  },
  {
    id: 'utility-color-picker',
    name: '颜色选择器',
    description: '选择颜色并获取多种格式的颜色值。',
    href: '/tools/utility/color-picker',
    icon: 'Palette',
    category: 'utility',
    popular: false,
    tags: ['颜色', '选择器', '格式'],
    difficulty: 'beginner',
    estimatedTime: '1-2分钟',
  },
  {
    id: 'utility-converter',
    name: '单位转换器',
    description: '转换长度、重量、温度等各种单位。',
    href: '/tools/utility/converter',
    icon: 'Calculator',
    category: 'utility',
    popular: false,
    tags: ['单位', '转换', '长度', '重量', '温度'],
    difficulty: 'beginner',
    estimatedTime: '即时',
  },
  {
    id: 'utility-data-generator',
    name: '数据生成器',
    description: '生成测试数据，支持多种格式和类型。',
    href: '/tools/utility/data-generator',
    icon: 'FileText',
    category: 'utility',
    popular: false,
    tags: ['数据', '生成', '测试', '假数据'],
    difficulty: 'intermediate',
    estimatedTime: '1-3分钟',
  },
  {
    id: 'utility-file-converter',
    name: '文件转换器',
    description: '转换各种文件格式，支持文档、图片等。',
    href: '/tools/utility/file-converter',
    icon: 'FileText',
    category: 'utility',
    popular: false,
    tags: ['文件', '转换', '格式', '文档'],
    difficulty: 'beginner',
    estimatedTime: '1-5分钟',
  },
  {
    id: 'utility-network-tools',
    name: '网络工具',
    description: 'IP查询、端口扫描等网络相关工具。',
    href: '/tools/utility/network-tools',
    icon: 'Send',
    category: 'utility',
    popular: false,
    tags: ['网络', 'IP', '端口', '查询'],
    difficulty: 'intermediate',
    estimatedTime: '1-5分钟',
  },
  {
    id: 'utility-random',
    name: '随机数生成器',
    description: '生成随机数、随机字符串等。',
    href: '/tools/utility/random',
    icon: 'Calculator',
    category: 'utility',
    popular: false,
    tags: ['随机数', '字符串', '生成'],
    difficulty: 'beginner',
    estimatedTime: '即时',
  },
  {
    id: 'utility-time-calculator',
    name: '时间计算器',
    description: '计算时间差、日期加减等时间相关计算。',
    href: '/tools/utility/time-calculator',
    icon: 'Clock',
    category: 'utility',
    popular: false,
    tags: ['时间', '计算', '日期', '时差'],
    difficulty: 'beginner',
    estimatedTime: '1-2分钟',
  },
  {
    id: 'utility-unit-converter',
    name: '单位转换器',
    description: '转换各种物理单位，支持长度、重量、温度等。',
    href: '/tools/utility/unit-converter',
    icon: 'Calculator',
    category: 'utility',
    popular: false,
    tags: ['单位', '转换', '物理'],
    difficulty: 'beginner',
    estimatedTime: '即时',
  },
  // 新增实用工具
  {
    id: 'utility-url-shortener',
    name: 'URL短链生成器',
    description: '生成短链接，方便分享和统计点击量。',
    href: '/tools/utility/url-shortener',
    icon: 'Link',
    category: 'utility',
    popular: true,
    new: true,
    tags: ['短链', 'URL', '分享', '统计'],
    difficulty: 'beginner',
    estimatedTime: '即时',
  },
  {
    id: 'utility-markdown-editor',
    name: 'Markdown编辑器',
    description: '在线Markdown编辑器，支持实时预览和导出。',
    href: '/tools/utility/markdown-editor',
    icon: 'FileText',
    category: 'utility',
    popular: true,
    new: true,
    tags: ['Markdown', '编辑器', '预览', '导出'],
    difficulty: 'intermediate',
    estimatedTime: '5-30分钟',
  },
  {
    id: 'utility-todo-list',
    name: '待办事项管理',
    description: '简洁的待办事项管理工具，支持分类和优先级。',
    href: '/tools/utility/todo-list',
    icon: 'CheckSquare',
    category: 'utility',
    popular: false,
    new: true,
    tags: ['待办', '任务', '管理', '效率'],
    difficulty: 'beginner',
    estimatedTime: '持续使用',
  },
  {
    id: 'learn-calculator',
    name: '数学公式计算器',
    description: '支持复杂数学计算、科学计算、三角函数等。',
    href: '/tools/learn/calculator',
    icon: 'Calculator',
    category: 'learn',
    popular: true,
    tags: ['数学', '科学计算', '三角函数', '公式'],
    difficulty: 'intermediate',
    estimatedTime: '2-10分钟',
  },
  {
    id: 'learn-cheatsheet',
    name: '速查表工具',
    description: '提供CSS、正则表达式、常用命令等速查功能。',
    href: '/tools/learn/cheatsheet',
    icon: 'BookOpen',
    category: 'learn',
    popular: false,
    tags: ['速查', 'CSS', '正则', '命令', '参考'],
    difficulty: 'beginner',
    estimatedTime: '查阅使用',
  },
  {
    id: 'learn-notes',
    name: '笔记工具',
    description: '在线笔记工具，支持Markdown格式。',
    href: '/tools/learn/notes',
    icon: 'FileText',
    category: 'learn',
    popular: false,
    tags: ['笔记', 'Markdown', '学习', '记录'],
    difficulty: 'beginner',
    estimatedTime: '持续使用',
  },
  {
    id: 'learn-progress',
    name: '学习进度跟踪',
    description: '跟踪学习进度，设置目标和里程碑。',
    href: '/tools/learn/progress',
    icon: 'BookOpen',
    category: 'learn',
    popular: false,
    tags: ['进度', '目标', '学习', '跟踪'],
    difficulty: 'beginner',
    estimatedTime: '持续使用',
  },
  // 新增学习工具
  {
    id: 'learn-flashcards',
    name: '记忆卡片',
    description: '创建和使用记忆卡片，提高学习效率。',
    href: '/tools/learn/flashcards',
    icon: 'Layers',
    category: 'learn',
    popular: true,
    new: true,
    tags: ['记忆', '卡片', '学习', '复习'],
    difficulty: 'beginner',
    estimatedTime: '5-30分钟',
  },
  {
    id: 'learn-pomodoro',
    name: '番茄工作法',
    description: '番茄工作法计时器，提高专注力和工作效率。',
    href: '/tools/learn/pomodoro',
    icon: 'Timer',
    category: 'learn',
    popular: true,
    new: true,
    tags: ['番茄工作法', '专注', '效率', '计时'],
    difficulty: 'beginner',
    estimatedTime: '25分钟/轮',
  },
  {
    id: 'health-bmi',
    name: 'BMI计算器',
    description: '计算身体质量指数，评估健康状态。',
    href: '/tools/health/bmi',
    icon: 'Calculator',
    category: 'health',
    popular: false,
    tags: ['BMI', '健康', '体重', '指数'],
    difficulty: 'beginner',
    estimatedTime: '1分钟',
  },
  {
    id: 'health-calorie',
    name: '卡路里计算器',
    description: '计算每日所需卡路里，制定饮食计划。',
    href: '/tools/health/calorie',
    icon: 'Calculator',
    category: 'health',
    popular: false,
    tags: ['卡路里', '饮食', '健康', '计划'],
    difficulty: 'beginner',
    estimatedTime: '2-3分钟',
  },
  // 新增健康工具
  {
    id: 'health-water-reminder',
    name: '喝水提醒器',
    description: '设置喝水提醒，养成健康饮水习惯。',
    href: '/tools/health/water-reminder',
    icon: 'Droplets',
    category: 'health',
    popular: false,
    new: true,
    tags: ['喝水', '提醒', '健康', '习惯'],
    difficulty: 'beginner',
    estimatedTime: '持续使用',
  },
  {
    id: 'health-sleep-tracker',
    name: '睡眠记录器',
    description: '记录和分析睡眠质量，改善睡眠习惯。',
    href: '/tools/health/sleep-tracker',
    icon: 'Moon',
    category: 'health',
    popular: false,
    new: true,
    tags: ['睡眠', '记录', '分析', '健康'],
    difficulty: 'beginner',
    estimatedTime: '持续使用',
  },
  // 媒体工具
  {
    id: 'media-audio-converter',
    name: '音频格式转换',
    description: '转换音频文件格式，支持MP3、WAV、AAC等。',
    href: '/tools/media/audio-converter',
    icon: 'Music',
    category: 'media',
    popular: true,
    new: true,
    tags: ['音频', '转换', 'MP3', 'WAV', 'AAC'],
    difficulty: 'beginner',
    estimatedTime: '1-5分钟',
  },
  {
    id: 'media-video-compressor',
    name: '视频压缩工具',
    description: '压缩视频文件大小，保持画质。',
    href: '/tools/media/video-compressor',
    icon: 'Video',
    category: 'media',
    popular: true,
    new: true,
    tags: ['视频', '压缩', '大小', '画质'],
    difficulty: 'intermediate',
    estimatedTime: '2-10分钟',
  },
  {
    id: 'media-gif-maker',
    name: 'GIF制作器',
    description: '从视频或图片序列制作GIF动图。',
    href: '/tools/media/gif-maker',
    icon: 'Image',
    category: 'media',
    popular: true,
    new: true,
    tags: ['GIF', '动图', '制作', '视频'],
    difficulty: 'intermediate',
    estimatedTime: '2-5分钟',
  },
  // 办公工具
  {
    id: 'office-pdf-tools',
    name: 'PDF工具集',
    description: 'PDF合并、分割、转换等多功能工具。',
    href: '/tools/office/pdf-tools',
    icon: 'FileText',
    category: 'office',
    popular: true,
    new: true,
    tags: ['PDF', '合并', '分割', '转换', '文档'],
    difficulty: 'beginner',
    estimatedTime: '1-5分钟',
  },
  {
    id: 'office-excel-converter',
    name: 'Excel转换器',
    description: '将Excel文件转换为CSV、JSON等格式。',
    href: '/tools/office/excel-converter',
    icon: 'FileSpreadsheet',
    category: 'office',
    popular: false,
    new: true,
    tags: ['Excel', 'CSV', 'JSON', '转换', '表格'],
    difficulty: 'beginner',
    estimatedTime: '1-3分钟',
  },
  {
    id: 'office-invoice-generator',
    name: '发票生成器',
    description: '快速生成专业发票模板。',
    href: '/tools/office/invoice-generator',
    icon: 'Receipt',
    category: 'office',
    popular: false,
    new: true,
    tags: ['发票', '模板', '生成', '商务'],
    difficulty: 'intermediate',
    estimatedTime: '5-10分钟',
  },
  // 安全工具
  {
    id: 'security-password-checker',
    name: '密码强度检测',
    description: '检测密码强度，提供安全建议。',
    href: '/tools/security/password-checker',
    icon: 'Shield',
    category: 'security',
    popular: true,
    new: true,
    tags: ['密码', '安全', '强度', '检测'],
    difficulty: 'beginner',
    estimatedTime: '即时',
  },
  {
    id: 'security-hash-generator',
    name: '哈希生成器',
    description: '生成MD5、SHA1、SHA256等哈希值。',
    href: '/tools/security/hash-generator',
    icon: 'Hash',
    category: 'security',
    popular: false,
    new: true,
    tags: ['哈希', 'MD5', 'SHA1', 'SHA256', '加密'],
    difficulty: 'intermediate',
    estimatedTime: '即时',
  },
  {
    id: 'security-uuid-generator',
    name: 'UUID生成器',
    description: '生成唯一标识符UUID，支持多种版本。',
    href: '/tools/security/uuid-generator',
    icon: 'Key',
    category: 'security',
    popular: false,
    new: true,
    tags: ['UUID', '唯一标识', '生成', '标识符'],
    difficulty: 'beginner',
    estimatedTime: '即时',
  },
  // 新增数据分析分类
  {
    id: 'data-csv-analyzer',
    name: 'CSV数据分析',
    description: '分析CSV文件数据，生成统计报告和图表。',
    href: '/tools/data/csv-analyzer',
    icon: 'BarChart',
    category: 'data',
    popular: true,
    new: true,
    tags: ['CSV', '数据分析', '统计', '图表'],
    difficulty: 'intermediate',
    estimatedTime: '3-10分钟',
  },
  {
    id: 'data-json-explorer',
    name: 'JSON数据探索器',
    description: '可视化探索JSON数据结构，支持搜索和过滤。',
    href: '/tools/data/json-explorer',
    icon: 'Search',
    category: 'data',
    popular: false,
    new: true,
    tags: ['JSON', '探索', '可视化', '搜索'],
    difficulty: 'intermediate',
    estimatedTime: '2-5分钟',
  },
  {
    id: 'data-chart-generator',
    name: '图表生成器',
    description: '从数据生成各种类型的图表和可视化。',
    href: '/tools/data/chart-generator',
    icon: 'PieChart',
    category: 'data',
    popular: true,
    new: true,
    tags: ['图表', '可视化', '数据', '生成'],
    difficulty: 'intermediate',
    estimatedTime: '3-8分钟',
  },
];

export const categories = [
  { id: 'all', name: '全部' },
  { id: 'ai', name: 'AI工具' },
  { id: 'text', name: '文本工具' },
  { id: 'image', name: '图片工具' },
  { id: 'dev', name: '开发工具' },
  { id: 'utility', name: '实用工具' },
  { id: 'learn', name: '学习工具' },
  { id: 'health', name: '健康工具' },
  { id: 'media', name: '媒体工具' },
  { id: 'office', name: '办公工具' },
  { id: 'security', name: '安全工具' },
  { id: 'data', name: '数据分析' }, // 新增分类
];

// 根据路径获取工具信息
export function getToolByPath(path: string): Tool | null {
  // 标准化路径：移除末尾斜杠
  const normalizedPath = path.endsWith('/') ? path.slice(0, -1) : path;
  
  // 精确匹配
  const exactMatch = tools.find(tool => tool.href === normalizedPath);
  if (exactMatch) return exactMatch;
  
  // 如果精确匹配失败，尝试模糊匹配（移除开头的斜杠）
  const pathWithoutLeadingSlash = normalizedPath.startsWith('/') ? normalizedPath.slice(1) : normalizedPath;
  const toolWithoutLeadingSlash = tools.find(tool => {
    const toolPath = tool.href.startsWith('/') ? tool.href.slice(1) : tool.href;
    return toolPath === pathWithoutLeadingSlash;
  });
  
  return toolWithoutLeadingSlash || null;
}

// 根据工具ID获取工具信息
export function getToolById(id: string): Tool | null {
  return tools.find(tool => tool.id === id) || null;
}

// 获取所有工具名称（用于反馈选择）
export function getAllToolNames(): { id: string; name: string }[] {
  return tools.map(tool => ({ id: tool.id, name: tool.name }));
} 