export interface Tool {
  id: string;
  name: string;
  description: string;
  href: string;
  icon: string; // 改为字符串，存储图标名称
  category: string;
  popular?: boolean;
}

export const tools: Tool[] = [
  // AI工具
  {
    id: 'ai-text-generator',
    name: '文本生成器',
    description: '生成Lorem ipsum、假数据、随机文本等，支持多种生成类型。',
    href: '/tools/ai/text-generator',
    icon: 'MessageSquare',
    category: 'ai',
    popular: true,
  },
  {
    id: 'ai-language-detect',
    name: '语言检测',
    description: '自动识别文本的语言类型，支持中英日韩法德西俄阿等多种语言。',
    href: '/tools/ai/language-detect',
    icon: 'Brain',
    category: 'ai',
    popular: true,
  },
  {
    id: 'ai-keyword-extract',
    name: '关键词提取',
    description: '从文本中智能提取关键词和短语，提供频率统计和重要性评分。',
    href: '/tools/ai/keyword-extract',
    icon: 'Hash',
    category: 'ai',
    popular: true,
  },
  {
    id: 'ai-text-summary',
    name: '智能摘要',
    description: '提取文本关键信息，生成简洁摘要（即将推出）。',
    href: '/tools/ai/text-summary',
    icon: 'Sparkles',
    category: 'ai',
    popular: false,
  },
  {
    id: 'ai-sentiment-analysis',
    name: '情感分析',
    description: '分析文本的情感倾向和语调（即将推出）。',
    href: '/tools/ai/sentiment-analysis',
    icon: 'TrendingUp',
    category: 'ai',
    popular: false,
  },
  {
    id: 'text-case',
    name: '文本格式转换',
    description: '快速转换文本大小写、驼峰命名等格式，支持9种常用格式。',
    href: '/tools/text/case',
    icon: 'TextCursorInput',
    category: 'text',
    popular: true,
  },
  {
    id: 'text-encode',
    name: '编码解码工具',
    description: 'Base64、URL、HTML等编码解码工具，支持多种格式转换。',
    href: '/tools/text/encode',
    icon: 'Code',
    category: 'text',
    popular: false,
  },
  {
    id: 'text-regex',
    name: '正则表达式测试',
    description: '在线测试和调试正则表达式，实时查看匹配结果。',
    href: '/tools/text/regex',
    icon: 'FileText',
    category: 'text',
    popular: true,
  },
  {
    id: 'text-analyze',
    name: '文本分析工具',
    description: '分析文本的字符数、词数、行数等统计信息。',
    href: '/tools/text/analyze',
    icon: 'FileText',
    category: 'text',
    popular: false,
  },
  {
    id: 'text-compare',
    name: '文本比较工具',
    description: '比较两段文本的差异，支持忽略大小写和空白字符。',
    href: '/tools/text/compare',
    icon: 'FileText',
    category: 'text',
    popular: false,
  },
  {
    id: 'text-deduplicate',
    name: '文本去重工具',
    description: '去除重复的文本行，支持多种去重模式。',
    href: '/tools/text/deduplicate',
    icon: 'FileText',
    category: 'text',
    popular: false,
  },
  {
    id: 'text-stats',
    name: '文本统计工具',
    description: '统计文本的字符、单词、行数等详细信息。',
    href: '/tools/text/stats',
    icon: 'FileText',
    category: 'text',
    popular: false,
  },
  {
    id: 'text-character-counter',
    name: '字符计数器',
    description: '实时统计文本字符数、词数、行数，支持多种统计模式。',
    href: '/tools/text/character-counter',
    icon: 'Hash',
    category: 'text',
    popular: true,
  },
  {
    id: 'text-markdown-editor',
    name: 'Markdown编辑器',
    description: '在线Markdown编辑器，支持实时预览和语法高亮。',
    href: '/tools/text/markdown-editor',
    icon: 'FileText',
    category: 'text',
    popular: true,
  },
  {
    id: 'image-compress',
    name: '图片压缩工具',
    description: '在线压缩图片，优化图片大小，支持质量调节。',
    href: '/tools/image/compress',
    icon: 'Image',
    category: 'image',
    popular: true,
  },
      {
      id: 'image-convert',
      name: '图片格式转换',
      description: '基于Canvas API的真实图片格式转换，支持主流格式间的高质量转换。',
      href: '/tools/image/convert',
    icon: 'Image',
    category: 'image',
    popular: false,
  },
  {
    id: 'image-watermark',
    name: '水印添加工具',
    description: '为图片添加文字水印，支持自定义位置、颜色、透明度等。',
    href: '/tools/image/watermark',
    icon: 'Image',
    category: 'image',
    popular: false,
  },
  {
    id: 'image-resize',
    name: '图片尺寸调整',
    description: '调整图片尺寸，支持保持比例、批量处理等功能。',
    href: '/tools/image/resize',
    icon: 'Image',
    category: 'image',
    popular: false,
  },
  {
    id: 'image-filter',
    name: '图片滤镜工具',
    description: '为图片添加各种滤镜效果，支持亮度、对比度、饱和度调节。',
    href: '/tools/image/filter',
    icon: 'Image',
    category: 'image',
    popular: false,
  },
  {
    id: 'dev-format',
    name: '代码格式化',
    description: '格式化JavaScript、JSON、CSS等代码，使其更易读。',
    href: '/tools/dev/format',
    icon: 'Code',
    category: 'dev',
    popular: true,
  },
  {
    id: 'dev-json',
    name: 'JSON工具',
    description: '格式化、验证、压缩JSON数据，支持自定义缩进。',
    href: '/tools/dev/json',
    icon: 'Code',
    category: 'dev',
    popular: false,
  },
  {
    id: 'dev-color',
    name: '颜色选择器',
    description: '选择颜色并获取多种格式的颜色值，支持RGB、HSL、HEX等格式。',
    href: '/tools/dev/color',
    icon: 'Palette',
    category: 'dev',
    popular: true,
  },
  {
    id: 'dev-api',
    name: 'API测试工具',
    description: '测试API接口，发送HTTP请求并查看响应结果。',
    href: '/tools/dev/api',
    icon: 'Send',
    category: 'dev',
    popular: true,
  },
  {
    id: 'dev-timestamp',
    name: '时间戳转换',
    description: '时间戳与日期时间相互转换，支持多种格式。',
    href: '/tools/dev/timestamp',
    icon: 'Clock',
    category: 'dev',
    popular: false,
  },
  {
    id: 'dev-gradient-generator',
    name: '渐变生成器',
    description: '生成CSS渐变代码，支持线性和径向渐变，可视化编辑。',
    href: '/tools/dev/gradient-generator',
    icon: 'Palette',
    category: 'dev',
    popular: true,
  },
  {
    id: 'dev-image-to-base64',
    name: '图片转Base64',
    description: '将图片转换为Base64编码，方便在代码中使用。',
    href: '/tools/dev/image-to-base64',
    icon: 'Image',
    category: 'dev',
    popular: false,
  },
  {
    id: 'utility-qr',
    name: '二维码生成器',
    description: '生成自定义二维码，支持文本和URL，可下载使用。',
    href: '/tools/utility/qr',
    icon: 'QrCode',
    category: 'utility',
    popular: true,
  },
  {
    id: 'utility-password',
    name: '密码生成器',
    description: '生成安全、随机的密码，支持自定义长度和字符类型。',
    href: '/tools/utility/password',
    icon: 'Shield',
    category: 'utility',
    popular: false,
  },
  {
    id: 'utility-calculator',
    name: '计算器',
    description: '基础计算器，支持加减乘除等基本运算。',
    href: '/tools/utility/calculator',
    icon: 'Calculator',
    category: 'utility',
    popular: false,
  },
  {
    id: 'utility-color-picker',
    name: '颜色选择器',
    description: '选择颜色并获取多种格式的颜色值。',
    href: '/tools/utility/color-picker',
    icon: 'Palette',
    category: 'utility',
    popular: false,
  },
  {
    id: 'utility-converter',
    name: '单位转换器',
    description: '转换长度、重量、温度等各种单位。',
    href: '/tools/utility/converter',
    icon: 'Calculator',
    category: 'utility',
    popular: false,
  },
  {
    id: 'utility-data-generator',
    name: '数据生成器',
    description: '生成测试数据，支持多种格式和类型。',
    href: '/tools/utility/data-generator',
    icon: 'FileText',
    category: 'utility',
    popular: false,
  },
  {
    id: 'utility-file-converter',
    name: '文件转换器',
    description: '转换各种文件格式，支持文档、图片等。',
    href: '/tools/utility/file-converter',
    icon: 'FileText',
    category: 'utility',
    popular: false,
  },
  {
    id: 'utility-network-tools',
    name: '网络工具',
    description: 'IP查询、端口扫描等网络相关工具。',
    href: '/tools/utility/network-tools',
    icon: 'Send',
    category: 'utility',
    popular: false,
  },
  {
    id: 'utility-random',
    name: '随机数生成器',
    description: '生成随机数、随机字符串等。',
    href: '/tools/utility/random',
    icon: 'Calculator',
    category: 'utility',
    popular: false,
  },
  {
    id: 'utility-time-calculator',
    name: '时间计算器',
    description: '计算时间差、日期加减等时间相关计算。',
    href: '/tools/utility/time-calculator',
    icon: 'Clock',
    category: 'utility',
    popular: false,
  },
  {
    id: 'utility-unit-converter',
    name: '单位转换器',
    description: '转换各种物理单位，支持长度、重量、温度等。',
    href: '/tools/utility/unit-converter',
    icon: 'Calculator',
    category: 'utility',
    popular: false,
  },
  {
    id: 'utility-browser-info',
    name: '浏览器信息',
    description: '查看浏览器详细信息、屏幕分辨率、用户代理等。',
    href: '/tools/utility/browser-info',
    icon: 'Monitor',
    category: 'utility',
    popular: false,
  },
  {
    id: 'utility-pomodoro-timer',
    name: '番茄钟计时器',
    description: '专注工作计时器，帮助提高工作效率和专注度。',
    href: '/tools/utility/pomodoro-timer',
    icon: 'Clock',
    category: 'utility',
    popular: true,
  },
  {
    id: 'utility-speed-test',
    name: '网速测试',
    description: '测试网络连接速度，检测延迟和带宽。',
    href: '/tools/utility/speed-test',
    icon: 'Wifi',
    category: 'utility',
    popular: false,
  },
  {
    id: 'utility-gps-coordinates',
    name: 'GPS坐标工具',
    description: '获取地理位置坐标，坐标格式转换。',
    href: '/tools/utility/gps-coordinates',
    icon: 'MapPin',
    category: 'utility',
    popular: false,
  },
  {
    id: 'utility-compound-calculator',
    name: '复利计算器',
    description: '计算投资复利收益，制定理财计划。',
    href: '/tools/utility/compound-calculator',
    icon: 'TrendingUp',
    category: 'utility',
    popular: false,
  },
  {
    id: 'utility-mortgage-calculator',
    name: '抵押贷款计算器',
    description: '计算房屋贷款的月供、总利息和还款计划，支持多种贷款参数。',
    href: '/tools/utility/mortgage-calculator',
    icon: 'Calculator',
    category: 'utility',
    popular: true,
  },
  {
    id: 'utility-investment-calculator',
    name: '投资收益计算器',
    description: '计算长期投资的复利收益和增长轨迹，支持定投模式。',
    href: '/tools/utility/investment-calculator',
    icon: 'TrendingUp',
    category: 'utility',
    popular: true,
  },
  {
    id: 'utility-habit-tracker',
    name: '习惯追踪器',
    description: '记录和追踪日常习惯，培养良好生活方式，支持目标设定。',
    href: '/tools/utility/habit-tracker',
    icon: 'Target',
    category: 'utility',
    popular: true,
  },
  {
    id: 'utility-lucky-wheel',
    name: '幸运转盘',
    description: '自定义选项的抽奖转盘，支持旋转动画和历史记录。',
    href: '/tools/utility/lucky-wheel',
    icon: 'RotateCw',
    category: 'utility',
    popular: false,
  },
  {
    id: 'utility-ascii-art',
    name: 'ASCII艺术生成器',
    description: '将文本转换为ASCII艺术字，支持多种字体样式和导出功能。',
    href: '/tools/utility/ascii-art',
    icon: 'Type',
    category: 'utility',
    popular: false,
  },
  {
    id: 'utility-color-palette-generator',
    name: '配色方案生成器',
    description: '根据色彩理论生成和谐的配色方案，支持多种配色规则和导出功能。',
    href: '/tools/utility/color-palette-generator',
    icon: 'Palette',
    category: 'utility',
    popular: true,
  },
  {
    id: 'utility-dice-simulator',
    name: '骰子模拟器',
    description: '虚拟骰子投掷器，支持多种骰子类型、数量设置和投掷动画。',
    href: '/tools/utility/dice-simulator',
    icon: 'Dices',
    category: 'utility',
    popular: false,
  },
  {
    id: 'learn-calculator',
    name: '数学公式计算器',
    description: '支持复杂数学计算、科学计算、三角函数等。',
    href: '/tools/learn/calculator',
    icon: 'Calculator',
    category: 'learn',
    popular: true,
  },
  {
    id: 'learn-cheatsheet',
    name: '速查表工具',
    description: '提供CSS、正则表达式、常用命令等速查功能。',
    href: '/tools/learn/cheatsheet',
    icon: 'BookOpen',
    category: 'learn',
    popular: false,
  },
  {
    id: 'learn-notes',
    name: '笔记工具',
    description: '在线笔记工具，支持Markdown格式。',
    href: '/tools/learn/notes',
    icon: 'FileText',
    category: 'learn',
    popular: false,
  },
  {
    id: 'learn-progress',
    name: '学习进度跟踪',
    description: '跟踪学习进度，设置目标和里程碑。',
    href: '/tools/learn/progress',
    icon: 'BookOpen',
    category: 'learn',
    popular: false,
  },
  {
    id: 'health-bmi',
    name: 'BMI计算器',
    description: '计算身体质量指数，评估健康状态。',
    href: '/tools/health/bmi',
    icon: 'Calculator',
    category: 'health',
    popular: false,
  },
    {
    id: 'health-calorie',
    name: '卡路里计算器',
    description: '计算每日所需卡路里，制定饮食计划。',
    href: '/tools/health/calorie',
    icon: 'Calculator',
    category: 'health',
    popular: false,
  },
  // 媒体工具
  {
    id: 'media-player',
    name: '媒体播放器',
    description: '支持音频和视频播放，包含格式转换、剪辑等功能。',
    href: '/tools/media',
    icon: 'Play',
    category: 'media',
    popular: true,
  },
  // 办公工具
  {
    id: 'office-document-processor',
    name: '文档处理器',
    description: '文本处理、表格生成、CSV/JSON转换等办公相关工具。',
    href: '/tools/office',
    icon: 'FileText',
    category: 'office',
    popular: true,
  },
  // 安全工具
  {
    id: 'security-tools',
    name: '安全工具集',
    description: '哈希计算、加密解密、密码强度检测、SSL证书检查等安全工具。',
    href: '/tools/security',
    icon: 'Shield',
    category: 'security',
    popular: true,
  },
  {
    id: 'security-password-strength',
    name: '密码强度检测',
    description: '检测密码安全强度，提供改进建议，确保密码安全。',
    href: '/tools/security/password-strength',
    icon: 'Key',
    category: 'security',
    popular: true,
  },
  // 新增金融理财工具
  {
    id: 'finance-currency-converter',
    name: '汇率转换器',
    description: '实时汇率转换，支持全球主要货币，数据来源可靠。',
    href: '/tools/finance/currency-converter',
    icon: 'DollarSign',
    category: 'finance',
    popular: true,
  },
  {
    id: 'finance-loan-calculator',
    name: '贷款计算器',
    description: '计算房贷、车贷等各种贷款的月供、利息和总额。',
    href: '/tools/finance/loan-calculator',
    icon: 'Calculator',
    category: 'finance',
    popular: false,
  },
  {
    id: 'finance-investment-calculator',
    name: '投资回报计算器',
    description: '计算投资收益、复利增长和投资回报率。',
    href: '/tools/finance/investment-calculator',
    icon: 'TrendingUp',
    category: 'finance',
    popular: false,
  },
  {
    id: 'finance-tip-calculator',
    name: '小费计算器',
    description: '快速计算餐厅小费和人均分摊金额。',
    href: '/tools/finance/tip-calculator',
    icon: 'Receipt',
    category: 'finance',
    popular: false,
  },
  {
    id: 'finance-tax-calculator',
    name: '税费计算器',
    description: '计算个人所得税、增值税等各种税费。',
    href: '/tools/finance/tax-calculator',
    icon: 'FileText',
    category: 'finance',
    popular: false,
  },
  // 新增设计工具
  {
    id: 'design-css-generator',
    name: 'CSS代码生成器',
    description: '可视化生成CSS代码，包括阴影、边框、动画等效果。',
    href: '/tools/design/css-generator',
    icon: 'Palette',
    category: 'design',
    popular: true,
  },
  {
    id: 'design-icon-generator',
    name: '图标生成器',
    description: '在线生成各种风格的图标，支持SVG和PNG格式。',
    href: '/tools/design/icon-generator',
    icon: 'Star',
    category: 'design',
    popular: false,
  },
  {
    id: 'design-color-palette',
    name: '配色方案生成器',
    description: '生成和谐的配色方案，提供多种配色规则。',
    href: '/tools/design/color-palette',
    icon: 'Palette',
    category: 'design',
    popular: true,
  },
  {
    id: 'design-favicon-generator',
    name: 'Favicon生成器',
    description: '从图片生成各种尺寸的网站图标文件。',
    href: '/tools/design/favicon-generator',
    icon: 'Globe',
    category: 'design',
    popular: false,
  },
  {
    id: 'design-logo-maker',
    name: '简易Logo制作',
    description: '快速制作简单的文字Logo和图形Logo。',
    href: '/tools/design/logo-maker',
    icon: 'Zap',
    category: 'design',
    popular: false,
  },
  // 新增社交媒体工具
  {
    id: 'social-link-shortener',
    name: '链接缩短器',
    description: '创建短链接，支持自定义别名和点击统计。',
    href: '/tools/social/link-shortener',
    icon: 'Link',
    category: 'social',
    popular: true,
  },
  {
    id: 'social-hashtag-generator',
    name: '话题标签生成器',
    description: '为社交媒体内容生成相关的话题标签。',
    href: '/tools/social/hashtag-generator',
    icon: 'Hash',
    category: 'social',
    popular: false,
  },
  {
    id: 'social-post-scheduler',
    name: '发布时间优化器',
    description: '分析最佳发布时间，提高社交媒体互动率。',
    href: '/tools/social/post-scheduler',
    icon: 'Clock',
    category: 'social',
    popular: false,
  },
  {
    id: 'social-bio-generator',
    name: '个人简介生成器',
    description: '为社交媒体账户生成吸引人的个人简介。',
    href: '/tools/social/bio-generator',
    icon: 'User',
    category: 'social',
    popular: false,
  },
  // 新增生产力工具
  {
    id: 'productivity-pomodoro',
    name: '番茄工作法计时器',
    description: '专注工作计时器，帮助提高工作效率和专注力。',
    href: '/tools/productivity/pomodoro',
    icon: 'Clock',
    category: 'productivity',
    popular: true,
  },
  {
    id: 'productivity-todo-list',
    name: '待办事项清单',
    description: '简洁的任务管理工具，支持优先级和分类。',
    href: '/tools/productivity/todo-list',
    icon: 'CheckSquare',
    category: 'productivity',
    popular: true,
  },
  {
    id: 'productivity-habit-tracker',
    name: '习惯追踪器',
    description: '追踪日常习惯，帮助养成良好的生活习惯。',
    href: '/tools/productivity/habit-tracker',
    icon: 'Target',
    category: 'productivity',
    popular: false,
  },
  {
    id: 'productivity-time-tracker',
    name: '时间追踪器',
    description: '记录工作时间，分析时间分配和工作效率。',
    href: '/tools/productivity/time-tracker',
    icon: 'Timer',
    category: 'productivity',
    popular: false,
  },
  // 新增游戏娱乐工具
  {
    id: 'game-random-picker',
    name: '随机选择器',
    description: '从列表中随机选择项目，支持权重设置。',
    href: '/tools/game/random-picker',
    icon: 'Shuffle',
    category: 'game',
    popular: true,
  },
  {
    id: 'game-dice-roller',
    name: '骰子模拟器',
    description: '模拟投掷各种类型的骰子，支持多个骰子。',
    href: '/tools/game/dice-roller',
    icon: 'Dices',
    category: 'game',
    popular: false,
  },
  {
    id: 'game-lottery',
    name: '抽奖工具',
    description: '公平的抽奖工具，支持多种抽奖模式。',
    href: '/tools/game/lottery',
    icon: 'Gift',
    category: 'game',
    popular: false,
  },
  {
    id: 'game-word-game',
    name: '单词游戏',
    description: '简单的单词猜测游戏，寓教于乐。',
    href: '/tools/game/word-game',
    icon: 'BookOpen',
    category: 'game',
    popular: false,
  },
  // 新增测量工具
  {
    id: 'measure-screen-ruler',
    name: '屏幕尺子',
    description: '在屏幕上测量像素距离和尺寸。',
    href: '/tools/measure/screen-ruler',
    icon: 'Ruler',
    category: 'measure',
    popular: true,
  },
  {
    id: 'measure-color-picker',
    name: '屏幕取色器',
    description: '从屏幕任意位置获取颜色值。',
    href: '/tools/measure/color-picker',
    icon: 'Eyedropper',
    category: 'measure',
    popular: false,
  },
  {
    id: 'measure-pixel-density',
    name: '像素密度检测',
    description: '检测设备的像素密度和屏幕信息。',
    href: '/tools/measure/pixel-density',
    icon: 'Monitor',
    category: 'measure',
    popular: false,
  },
  {
    id: 'measure-viewport-size',
    name: '视口尺寸检测',
    description: '检测浏览器视口尺寸和设备信息。',
    href: '/tools/measure/viewport-size',
    icon: 'Maximize',
    category: 'measure',
    popular: false,
  },
];

export const categories = [
  { id: 'all', name: '全部' },
  { id: 'ai', name: 'AI工具' },
  { id: 'text', name: '文本工具' },
  { id: 'image', name: '图片工具' },
  { id: 'dev', name: '开发工具' },
  { id: 'utility', name: '实用工具' },
  { id: 'learn', name: '学习工具' },
  { id: 'health', name: '健康工具' },
  { id: 'media', name: '媒体工具' },
  { id: 'office', name: '办公工具' },
  { id: 'security', name: '安全工具' },
  { id: 'finance', name: '金融理财' },
  { id: 'design', name: '设计工具' },
  { id: 'social', name: '社交媒体' },
  { id: 'productivity', name: '生产力' },
  { id: 'game', name: '游戏娱乐' },
  { id: 'measure', name: '测量工具' },
];

// 根据路径获取工具信息
export function getToolByPath(path: string): Tool | null {
  // 标准化路径：移除末尾斜杠
  const normalizedPath = path.endsWith('/') ? path.slice(0, -1) : path;
  
  // 精确匹配
  const exactMatch = tools.find(tool => tool.href === normalizedPath);
  if (exactMatch) return exactMatch;
  
  // 如果精确匹配失败，尝试模糊匹配（移除开头的斜杠）
  const pathWithoutLeadingSlash = normalizedPath.startsWith('/') ? normalizedPath.slice(1) : normalizedPath;
  const toolWithoutLeadingSlash = tools.find(tool => {
    const toolPath = tool.href.startsWith('/') ? tool.href.slice(1) : tool.href;
    return toolPath === pathWithoutLeadingSlash;
  });
  
  return toolWithoutLeadingSlash || null;
}

// 根据工具ID获取工具信息
export function getToolById(id: string): Tool | null {
  return tools.find(tool => tool.id === id) || null;
}

// 获取所有工具名称（用于反馈选择）
export function getAllToolNames(): { id: string; name: string }[] {
  return tools.map(tool => ({ id: tool.id, name: tool.name }));
} 